[package]
name = "snare"
description = "GitHub webhooks runner daemon"
version = "0.4.2"
homepage = "https://tratt.net/laurie/src/snare/"
repository = "https://github.com/softdevteam/snare/"
authors = ["Laurence Tratt <laurie@tratt.net>"]
readme = "README.md"
license = "Apache-2.0 OR MIT"
categories = ["development-tools"]
keywords = ["github", "webhook"]
edition = "2018"

[build-dependencies]
cfgrammar = { path="../grmtools/cfgrammar"}
lrlex = { path="../grmtools/lrlex"}
lrpar = { path="../grmtools/lrpar"}
rerun_except = "1.0"

[dependencies]
cfgrammar = { path="../grmtools/cfgrammar"}
crypto-mac = "0.11"
getopts = "0.2"
hex = "0.4"
hmac = "0.11"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
json = "0.12"
libc = "0.2"
lrlex = { path="../grmtools/lrlex"}
lrpar = { path="../grmtools/lrpar"}
nix = "0.20"
num_cpus = "1.12"
percent-encoding = "2.1"
regex = "1.5"
secstr = "0.4"
sha-1 = "0.9"
signal-hook = "0.3"
tempfile = "3.1"
tokio = { version = "1.6", features = ["full"] }
users = "0.11"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
